version: '3.7'

services:
  neo4j:
    image: neo4j:4.4.12
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/testpassword
    ports:
      - "7474:7474"  # Browser UI
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data

  airflow:
    image: apache/airflow:2.7.0
    container_name: airflow
    depends_on:
      - neo4j
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: sqlite:////usr/local/airflow/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "true"
      AIRFLOW__CORE__FERNET_KEY: "your_fernet_key" # Replace with your fernet key
      AIRFLOW__WEBSERVER__SECRET_KEY: "your_secret_key" # Replace with your secret key
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    entrypoint: ["airflow", "standalone"]

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    depends_on:
      - neo4j
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data

volumes:
  neo4j_data:
  metabase_data:
